server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  # zipkin
  zipkin:
    base-url: http://127.0.0.1:9411
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0 # 采样百分比

  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999                  # 跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8080   # 指定控制台服务的地址
#      filter:
#        enabled: false

# 配置ribbon的负载均衡策略
# 调用的提供者的名称
server-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
# 开启Fegin对Sentinel的支持
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 192.168.1.10:9876 # MQ服务的地址
  producer:
    group: shop-order # 生产者组
